/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FilmsImport } from './routes/films'
import { Route as IndexImport } from './routes/index'
import { Route as FilmsFilmIdImport } from './routes/films_.$filmId'

// Create/Update Routes

const FilmsRoute = FilmsImport.update({
  id: '/films',
  path: '/films',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FilmsFilmIdRoute = FilmsFilmIdImport.update({
  id: '/films_/$filmId',
  path: '/films/$filmId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/films': {
      id: '/films'
      path: '/films'
      fullPath: '/films'
      preLoaderRoute: typeof FilmsImport
      parentRoute: typeof rootRoute
    }
    '/films_/$filmId': {
      id: '/films_/$filmId'
      path: '/films/$filmId'
      fullPath: '/films/$filmId'
      preLoaderRoute: typeof FilmsFilmIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/films': typeof FilmsRoute
  '/films/$filmId': typeof FilmsFilmIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/films': typeof FilmsRoute
  '/films/$filmId': typeof FilmsFilmIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/films': typeof FilmsRoute
  '/films_/$filmId': typeof FilmsFilmIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/films' | '/films/$filmId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/films' | '/films/$filmId'
  id: '__root__' | '/' | '/films' | '/films_/$filmId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FilmsRoute: typeof FilmsRoute
  FilmsFilmIdRoute: typeof FilmsFilmIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FilmsRoute: FilmsRoute,
  FilmsFilmIdRoute: FilmsFilmIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/films",
        "/films_/$filmId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/films": {
      "filePath": "films.tsx"
    },
    "/films_/$filmId": {
      "filePath": "films_.$filmId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
