/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as FilmsIndexImport } from './routes/films/index'
import { Route as FilmsRouterImport } from './routes/films/router'
import { Route as FilmsFilmIdImport } from './routes/films/$filmId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FilmsIndexRoute = FilmsIndexImport.update({
  id: '/films/',
  path: '/films/',
  getParentRoute: () => rootRoute,
} as any)

const FilmsRouterRoute = FilmsRouterImport.update({
  id: '/films/router',
  path: '/films/router',
  getParentRoute: () => rootRoute,
} as any)

const FilmsFilmIdRoute = FilmsFilmIdImport.update({
  id: '/films/$filmId',
  path: '/films/$filmId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/films/$filmId': {
      id: '/films/$filmId'
      path: '/films/$filmId'
      fullPath: '/films/$filmId'
      preLoaderRoute: typeof FilmsFilmIdImport
      parentRoute: typeof rootRoute
    }
    '/films/router': {
      id: '/films/router'
      path: '/films/router'
      fullPath: '/films/router'
      preLoaderRoute: typeof FilmsRouterImport
      parentRoute: typeof rootRoute
    }
    '/films/': {
      id: '/films/'
      path: '/films'
      fullPath: '/films'
      preLoaderRoute: typeof FilmsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/films/$filmId': typeof FilmsFilmIdRoute
  '/films/router': typeof FilmsRouterRoute
  '/films': typeof FilmsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/films/$filmId': typeof FilmsFilmIdRoute
  '/films/router': typeof FilmsRouterRoute
  '/films': typeof FilmsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/films/$filmId': typeof FilmsFilmIdRoute
  '/films/router': typeof FilmsRouterRoute
  '/films/': typeof FilmsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/films/$filmId' | '/films/router' | '/films'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/films/$filmId' | '/films/router' | '/films'
  id: '__root__' | '/' | '/films/$filmId' | '/films/router' | '/films/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FilmsFilmIdRoute: typeof FilmsFilmIdRoute
  FilmsRouterRoute: typeof FilmsRouterRoute
  FilmsIndexRoute: typeof FilmsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FilmsFilmIdRoute: FilmsFilmIdRoute,
  FilmsRouterRoute: FilmsRouterRoute,
  FilmsIndexRoute: FilmsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/films/$filmId",
        "/films/router",
        "/films/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/films/$filmId": {
      "filePath": "films/$filmId.tsx"
    },
    "/films/router": {
      "filePath": "films/router.tsx"
    },
    "/films/": {
      "filePath": "films/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
